### ISSUE TITLE
Unit test failing

### ISSUE THREAD

**Issue by Asshiah** [auth0-samples/auth0-react-samples#155]
It seems the App.test.js test suite is failing with the following error:
`
 renders without crashing

    TypeError: Cannot read property 'loading' of undefined

      20 |
      21 | const App = () => {
    > 22 |   const { loading } = useAuth0();
         |           ^
      23 |
      24 |   if (loading) {
      25 |     return <Loading />;

      at loading (src/App.js:22:11)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:15108:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17342:13)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:18486:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:347:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:397:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:454:31)
      at beginWork$$1 (node_modules/react-dom/cjs/react-dom.development.js:23217:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22211:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22185:22)
      at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:21878:11)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21419:22)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:24319:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:24347:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24436:10)
      at node_modules/react-dom/cjs/react-dom.development.js:24963:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21687:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24962:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:25042:12)
      at Object.render (src/App.test.js:7:12)
`

**Comment by stevehobbsdev** [comment]
Thanks for raising and apologies for the radio silence. The sample has since been updated with a [brand new SDK](https://github.com/auth0/auth0-react) and a basic suite of tests.
